# Generated by Django 6.0.8 on 2026-09-11 13:09

import django.db.models.deletion
import wagtail.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotsTxt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Rendered as # lines at the top of the file.",
                        verbose_name="Comment",
                    ),
                ),
                (
                    "groups",
                    wagtail.fields.StreamField(
                        [("group", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Emitted as # lines immediately before this group.",
                                    "label": "Comment",
                                    "required": False,
                                },
                            ),
                            1: (
                                "agent_ready.robots_txt.blocks.UserAgentCharBlock",
                                (),
                                {},
                            ),
                            2: (
                                "wagtail.blocks.ListBlock",
                                (1,),
                                {
                                    "default": [],
                                    "help_text": "Leave empty to apply this group to all crawlers (*).",
                                    "label": "User-agents",
                                },
                            ),
                            3: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": True, "label": "search", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "label": "ai-input",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "label": "ai-train",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "default": "/",
                                    "help_text": "One path per line.",
                                    "label": "Allow",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "One path per line.",
                                    "label": "Disallow",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("comment", 0),
                                        ("user_agents", 2),
                                        ("search", 3),
                                        ("ai_input", 4),
                                        ("ai_train", 5),
                                        ("allow", 6),
                                        ("disallow", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Groups",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robots_txt_documents",
                        to="wagtailcore.site",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "robots.txt",
                "verbose_name_plural": "robots.txt",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site",), name="unique_robots_txt_per_site"
                    )
                ],
            },
        ),
    ]
