# Generated by Django 6.0.7 on 2026-08-28 08:42

import uuid

import django.db.models.deletion
import wagtail.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmsTxt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Rendered as the H1. Required by the llms.txt spec.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Optional blockquote under the H1.",
                        verbose_name="Summary",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="The rest of the human-authored file: introduction, H2 sections, and lists of links.",
                        verbose_name="Body",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "llms.txt",
                "verbose_name_plural": "llms.txt",
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
